# {{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-rp-iam-app-deploy" .Release.Name }}
  namespace: {{ include "identity-access-management.namespace" . }}
  labels:
    {{- include "identity-access-management.labels" . | nindent 4 }}
    app: {{ printf "%s-rp-iam-app-deploy" .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-rp-iam-app-deploy" .Release.Name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ printf "%s-rp-iam-app-deploy" .Release.Name }}
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35
          command:
            - sh
            - -c
            - >
              until nc -z retailpulse-dev-auth-mysql.cl62ae2senvp.ap-southeast-1.rds.amazonaws.com 3306; do
                echo "Waiting for MySQL at retailpulse-dev-auth-mysql.cl62ae2senvp.ap-southeast-1.rds.amazonaws.com:3306...";
                sleep 5;
              done;
              echo "MySQL is ready!";
          env:
            - name: MYSQL_HOST
              value: retailpulse-dev-auth-mysql.cl62ae2senvp.ap-southeast-1.rds.amazonaws.com
            - name: MYSQL_PORT
              value: "3306"

      containers:
        - image: {{ .Values.app.image }}
          name: {{ printf "%s-rp-iam-app-pod" .Release.Name }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          ports:
            - containerPort: {{ .Values.app.port }}
          envFrom:
            - secretRef:
                name: auth-db
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: {{ .Values.app.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: {{ .Values.app.port }}
          #   initialDelaySeconds: 20
          #   periodSeconds: 5
          resources: {}
      volumes:
        - name: config-volume
          configMap:
            name: {{ printf "%s-rp-iam-app-cm" .Release.Name }}
# {{- end }}