apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-rp-iam-app-cm" .Release.Name }}
  namespace: {{ include "identity-access-management.namespace" . }}
  labels:
    {{- include "identity-access-management.labels" . | nindent 4 }}
data:
  application.yaml: |
{{- tpl (.Values.app.configYaml | 
  replace "MYSQL_HOST" (include "identity-access-management.userMysqlService" .) |
  replace "ORIGIN_URL" (include "identity-access-management.webURL" .) |
  replace "ORIGIN_PORT" (include "identity-access-management.webPort" .) 
  ) . | nindent 4 
}}