{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-rp-report-mongodb-pvc" .Release.Name }}
  namespace: {{ include "report.namespace" . }}
  labels:
    {{- include "report.labels" . | nindent 4 }}
spec:
  {{- if and (hasKey .Values "global") (hasKey .Values.global "storageClass") (ne .Values.global.storageClass "") }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- else if and (hasKey .Values.mongodb "storageClass") (ne .Values.mongodb.storageClass "") }}
  storageClassName: {{ .Values.mongodb.storageClass }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}
  {{- if .Values.mongodb.storageClassName }}
  storageClassName: {{ .Values.mongodb.storageClassName | quote }}
  {{- end }}
{{- end }}