{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "report.mongodbService" . }}
  namespace: {{ include "report.namespace" . }}
  labels:
    {{- include "report.labels" . | nindent 4 }}
    app: {{ printf "%s-rp-report-mongodb-deploy" .Release.Name }}
spec:
  selector:
    app: {{ printf "%s-rp-report-mongodb-deploy" .Release.Name }}
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: ClusterIP
{{- end }}