# Global namespace override (optional)
namespace: ns-retailpulse

# MySQL Configuration
mysql:
  enabled: true
  image: mysql:latest
  rootPassword: password
  database: RPSalesDB
  storage: 1Gi
  nodePort: 30309
  initSql: |
    -- MySQL dump 10.13  Distrib 9.3.0, for Linux (x86_64)
    --
    -- Host: localhost    Database: RPSalesDB
    -- ------------------------------------------------------
    -- Server version	9.3.0

    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!50503 SET NAMES utf8mb4 */;
    /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    /*!40103 SET TIME_ZONE='+00:00' */;
    /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

    --
    -- Table structure for table `sales_details`
    --

    DROP TABLE IF EXISTS `sales_details`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `sales_details` (
      `id` bigint NOT NULL AUTO_INCREMENT,
      `product_id` bigint NOT NULL,
      `quantity` int NOT NULL,
      `sales_price_per_unit` decimal(38,2) NOT NULL,
      `sale_id` bigint NOT NULL,
      PRIMARY KEY (`id`),
      KEY `FKmofh1590bbm744ll9r3aywtk` (`sale_id`),
      CONSTRAINT `FKmofh1590bbm744ll9r3aywtk` FOREIGN KEY (`sale_id`) REFERENCES `sales_transaction` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `sales_details`
    --

    LOCK TABLES `sales_details` WRITE;
    /*!40000 ALTER TABLE `sales_details` DISABLE KEYS */;
    /*!40000 ALTER TABLE `sales_details` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `sales_tax`
    --

    DROP TABLE IF EXISTS `sales_tax`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `sales_tax` (
      `id` bigint NOT NULL AUTO_INCREMENT,
      `tax_rate` decimal(38,2) DEFAULT NULL,
      `tax_type` enum('GST') DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `sales_tax`
    --

    LOCK TABLES `sales_tax` WRITE;
    /*!40000 ALTER TABLE `sales_tax` DISABLE KEYS */;
    INSERT INTO `sales_tax` (`id`, `tax_rate`, `tax_type`) VALUES (1, 0.09, 'GST');
    /*!40000 ALTER TABLE `sales_tax` ENABLE KEYS */;
    UNLOCK TABLES;

    --
    -- Table structure for table `sales_transaction`
    --

    DROP TABLE IF EXISTS `sales_transaction`;
    /*!40101 SET @saved_cs_client     = @@character_set_client */;
    /*!50503 SET character_set_client = utf8mb4 */;
    CREATE TABLE `sales_transaction` (
      `id` bigint NOT NULL AUTO_INCREMENT,
      `business_entity_id` bigint NOT NULL,
      `sales_tax_amount` decimal(38,2) DEFAULT NULL,
      `subtotal` decimal(38,2) DEFAULT NULL,
      `total` decimal(38,2) DEFAULT NULL,
      `transaction_date` datetime(6) NOT NULL,
      `sales_tax_id` bigint DEFAULT NULL,
      PRIMARY KEY (`id`),
      KEY `FK7wq54e1ubjodfnaph9fu12grq` (`sales_tax_id`),
      CONSTRAINT `FK7wq54e1ubjodfnaph9fu12grq` FOREIGN KEY (`sales_tax_id`) REFERENCES `sales_tax` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    /*!40101 SET character_set_client = @saved_cs_client */;

    --
    -- Dumping data for table `sales_transaction`
    --

    LOCK TABLES `sales_transaction` WRITE;
    /*!40000 ALTER TABLE `sales_transaction` DISABLE KEYS */;
    /*!40000 ALTER TABLE `sales_transaction` ENABLE KEYS */;
    UNLOCK TABLES;

# Sales App Configuration
app:
  enabled: true
  image: docker.io/casperyap/rp-sales-app:v0.1.0
  imagePullPolicy: Always
  port: 8085
  nodePort: 30085
  configYaml: |
    server:
      port: 8085

    auth:
      enabled: true
      origin: http://ORIGIN_URL:ORIGIN_PORT
      jwt:
        key:
          set:
            uri: http://IAM_SVC:IAM_PORT/oauth2/jwks

    spring:
      datasource:
        url: "jdbc:mysql://MYSQL_HOST:3306/RPSalesDB"
        username: "root"
        password: "password"
        driver-class-name: "com.mysql.cj.jdbc.Driver"

      jpa:
        hibernate:
          ddl-auto: "update"
        database-platform: "org.hibernate.dialect.MySQLDialect"
        show-sql: true

    inventory-service:
      url: "http://INVENTORY_SVC:8084"

    logging:
      level:
        root: "INFO"
        org.springframework.security: "TRACE"        
        com.retailpulse: "DEBUG"
        com.retailpulse.client: DEBUG 
        feign: DEBUG 
        com.retailpulse.config.FeignConfig: DEBUG 
      file:
        name: "logs/rp-sales.log"

    management:
      tracing:
        enabled: true
        sampling:
          probability: 1.0

dependencies:
  inventoryReleaseName: retailpulse-inventory
  iamReleaseName: retailpulse-iam  
  webURL: localhost
  webPort: 30080