# Global namespace override (optional)
namespace: ns-retailpulse

# Web App Configuration
app:
  enabled: true
  image: docker.io/casperyap/rp-web-app:v0.2.0
  imagePullPolicy: Always
  storage: 1Gi
  portType: NodePort # Options: ClusterIP, NodePort, LoadBalancer
  port: 8080
  nodePort: 30080

runtimeConfigYaml: |
  {
    "authConfig": {
      "issuer": "IAM_SVC",
      "requireHttps": false,
      "redirectUri": "WEB_SVC",
      "clientId": "client",
      "responseType": "code",
      "scope": "openid",
      "useSilentRefresh": true,
      "useHttpBasicAuth": false,
      "disablePKCE": false,
      "showDebugInformation": true
    },
    "apiConfig": {
      "user_api_url": "USER_SVC:USER_PORT/",
      "business_entity_api_url": "BUSINESS_ENTITY_SVC:BUSINESS_ENTITY_PORT/",
      "inventory_api_url": "INVENTORY_SVC:INVENTORY_PORT/",
      "sales_api_url": "SALES_SVC:SALES_PORT/",
      "report_api_url": "REPORT_SVC:REPORT_PORT/",
      "payment_api_url": "PAYMENT_SVC:PAYMENT_PORT/"
    },
    "environment": {
      "production": true,
      "authEnabled": true,
      "useRuntimeConfig": true,
      "devModeUser": "superadmin",
      "devModeRole": "ADMIN",
      "defaultPassword": "password1",
      "stripePublicKey": "pk_test_51Rwa98Fo0IYXjs5f0dEGfpQ9SuGE4NnsYHl5XvWMHq9o47V94yfNELzq5lnszDjJT8Yn8XTn2JoW5imJDJQfhLjq00EYYg7VPM"
    }
  }

# Ingress Configuration (Optional)
ingress:
  enabled: false
  className: ""
  hosts:
    - host: retailpulse.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # - secretName: chart-example-tls
  #   hosts:
  #     - retailpulse.local

dependencies:
  iamReleaseName: retailpulse-iam  
  userReleaseName: retailpulse-user
  businessEntityReleaseName: retailpulse-businessentity
  inventoryReleaseName: retailpulse-inventory
  salesReleaseName: retailpulse-sales
  reportReleaseName: retailpulse-report
  paymentReleaseName: retailpulse-payment
  