# Global namespace override (optional)
# Note: Namespace resources are often managed outside of individual charts.
# Set this if deploying to a specific namespace via this chart.
namespace: ns-retailpulse

# MongoDB Configuration
mongodb:
  enabled: true
  image: mongo:7
  storage: 5Gi
  port: 27017
  # storageClassName: "" # Uncomment/set to your cluster's class if needed, e.g., "standard"

# Report App Configuration
app:
  enabled: true
  image: docker.io/casperyap/rp-report-app:v0.2.0 
  imagePullPolicy: Always
  port: 8086
  nodePort: 30086
  portType: NodePort
  configYaml: |
    server:
      port: 8086

    auth:
      enabled: true
      origin: ORIGIN_URL
      jwt:
        key:
          set:
            uri: IAM_SVC/oauth2/jwks

    spring:
      data:
        mongodb:
          uri: "mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&tlsAllowInvalidHostnames=true"
          database: reportsdb
          
    app:
      gridfs:
        bucket: reports # GridFS bucket name (prefixes fs.files/fs.chunks)
        
    inventory:
      api:
        base-url: "INVENTORY_SVC" # Dynamically replaced

    logging:
      level:
        root: "INFO"
        org.springframework.security: "INFO"
        com.retailpulse: "DEBUG"
        com.example.report.infrastructure.feign: "INFO"
        org.springframework.cloud.openfeign: DEBUG
        feign: DEBUG
      file:
        name: "logs/report-service.log"
    
    management:
      tracing:
        enabled: true
        sampling:
          probability: 1.0
      endpoints:
        web:
          exposure:
            include: health, info, prometheus
        health:
          probes:
            enabled: true
          show-details: "never"

dependencies:
  inventoryReleaseName: "retailpulse-inventory" 
  iamReleaseName: "retailpulse-iam" 
  webURL: localhost
  webExternalPort: 30080