# traefik-values.yaml

# Expose Traefik via AWS LoadBalancer
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"

# Enable Traefik dashboard
dashboard:
  enabled: true
  ingressRoute:
    dashboard:
      enabled: true

api:
  insecure: true
  dashboard: true

# EntryPoints for HTTP and HTTPS
entryPoints:
  web:
    address: ":80"
  websecure:  
    address: ":443"

# Enable Kubernetes CRD and Ingress support
additionalArguments:
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

# # Enable Let's Encrypt with Route 53 DNS challenge
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: "you@example.com"
#       storage: /data/acme.json
#       dnsChallenge:
#         provider: route53
#         delayBeforeCheck: 0

# # Mount AWS credentials via secret (optional if using IRSA)
# env:
#   - name: AWS_ACCESS_KEY_ID
#     valueFrom:
#       secretKeyRef:
#         name: aws-route53-creds
#         key: accessKey
#   - name: AWS_SECRET_ACCESS_KEY
#     valueFrom:
#       secretKeyRef:
#         name: aws-route53-creds
#         key: secretKey

# Persistent volume for acme.json
persistence:
  enabled: true
  existingClaim: traefik-acme-pvc
  accessMode: ReadWriteOnce
  size: 1Gi
  path: /data
