apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-temp-pvc
  namespace: ns-retailpulse
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi