# Global namespace override (optional)
namespace: ns-retailpulse

# IAM App Configuration
app:
  enabled: true
  image: docker.io/casperyap/rp-iam-app:v0.1.0
  imagePullPolicy: Always
  port: 8081
  nodePort: 30081
  configYaml: |
    server:
      port: 8081

    auth:
      origin: http://ORIGIN_URL:ORIGIN_PORT

    spring:
      datasource:
        url: "jdbc:mysql://MYSQL_HOST:3306/RPUserDB"
        username: "root"
        password: "password"
        driver-class-name: "com.mysql.cj.jdbc.Driver"

      jpa:
        hibernate:
          ddl-auto: "update"
        database-platform: "org.hibernate.dialect.MySQLDialect"
        show-sql: true

    client:
      id: client
      name: retail-pulse
      redirect-uri: http://ORIGIN_URL:ORIGIN_PORT
      post-logout-redirect-uri: http://ORIGIN_URL:ORIGIN_PORT

    logging:
      level:
        root: "INFO"
        org.springframework.security: "INFO"
        com.retailpulse: "DEBUG"
      file:
        name: "logs/rp-iam.log"

dependencies:
  userReleaseName: retailpulse-user
  webURL: localhost
  webPort: 30080
