{{- if and .Values.kibana.enabled .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: {{ .Values.namespace }}
  {{- with .Values.kibana.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.kibana.ingress.ingressClassName }}
  ingressClassName: {{ .Values.kibana.ingress.ingressClassName }}
  {{- end }}
  rules:
    {{- range .Values.kibana.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: kibana
                port:
                  number: 5601
          {{- end }}
    {{- end }}
  {{- if .Values.kibana.ingress.tls }}
  tls:
    {{- range .Values.kibana.ingress.tls }}
    - hosts:
        {{- toYaml .hosts | nindent 8 }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
