apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.basePath: "{{ .Values.kibana.serverBasePath }}"
    server.rewriteBasePath: {{ .Values.kibana.serverRewriteBasePath }}
    elasticsearch.hosts: {{ toJson .Values.kibana.elasticsearchHosts }}
    # Add any other Kibana settings here if needed
