apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ printf "%s-rp-businessentity-app-cm" .Release.Name }}
  namespace: {{ include "business-entity-microservice.namespace" . }}
  labels:
{{- include "business-entity-microservice.labels" . | nindent 4 }}
data:
  application.yaml: |
{{- tpl (.Values.app.configYaml | replace "MYSQL_HOST" (printf "%s-rp-businessentity-sql-svc" .Release.Name) | replace "REDIS_HOST" (printf "%s-rp-businessentity-redis-svc" .Release.Name)) . | nindent 4 }}