apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-rp-businessentity-sql-svc" .Release.Name }}
  namespace: {{ include "business-entity-microservice.namespace" . }}
  labels:
    {{- include "business-entity-microservice.labels" . | nindent 4 }}
    name: {{ printf "%s-rp-businessentity-sql-svc" .Release.Name }}
    app: {{ printf "%s-rp-businessentity-sql-deploy" .Release.Name }}
spec:
  selector:
    app: {{ printf "%s-rp-businessentity-sql-deploy" .Release.Name }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: {{ .Values.mysql.nodePort }}
  type: NodePort