apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-rp-user-app-cm" .Release.Name }}
  namespace: {{ include "user.namespace" . }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
data:
  application.yaml: |
{{- tpl (.Values.app.configYaml | 
    replace "MYSQL_HOST" (include "user.mysqlService" .) |
    replace "ORIGIN_URL" (include "user.webURL" .) | 
    replace "ORIGIN_PORT" (include "user.webPort" .) |
    replace "IAM_SVC" (include "user.iamService" .) | 
    replace "IAM_PORT" (include "user.iamPort" .)
  ) . | nindent 4 
}}
