apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-rp-user-app-cm" .Release.Name }}
  namespace: {{ include "user.namespace" . }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
data:
  application.yaml: |
{{- tpl (.Values.app.configYaml | replace "MYSQL_HOST" (printf "%s-rp-user-sql-svc" .Release.Name)) . | nindent 4 }}