apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-rp-user-sql-pvc" .Release.Name }}
  namespace: {{ include "user.namespace" . }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}