apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rp-user-sql-secret" .Release.Name }}
  namespace: {{ include "user.namespace" . }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
  MYSQL_DATABASE: {{ .Values.mysql.database }}