{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-rp-sales-app-deploy" .Release.Name }}
  namespace: {{ include "sales.namespace" . }}
  labels:
    {{- include "sales.labels" . | nindent 4 }}
    app: {{ printf "%s-rp-sales-app-deploy" .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-rp-sales-app-deploy" .Release.Name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ printf "%s-rp-sales-app-deploy" .Release.Name }}
    spec:
      initContainers:
        # Wait for MySQL Service to be reachable
        - name: wait-for-mysql
          image: busybox:1.35
          command:
            - sh
            - -c
            - >
              until nc -z {{ include "sales.mysqlService" . }} 3306; do
                echo "Waiting for MySQL at {{ include "sales.mysqlService" . }}:3306...";
                sleep 5;
              done;
              echo "MySQL is ready!";
          env:
            - name: MYSQL_HOST
              value: {{ include "sales.mysqlService" . }}
            - name: MYSQL_PORT
              value: "3306"
      containers:
        - image: {{ .Values.app.image }}
          name: {{ printf "%s-rp-sales-app-pod" .Release.Name }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          ports:
            - containerPort: {{ .Values.app.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health # Adjust path if different
              port: {{ .Values.app.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health # Adjust path if different
              port: {{ .Values.app.port }}
            initialDelaySeconds: 20
            periodSeconds: 5
          resources: {}
      volumes:
        - name: config-volume
          configMap:
            name: {{ printf "%s-rp-sales-app-cm" .Release.Name }}
{{- end }}