{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-rp-sales-app-deploy" .Release.Name }}
  namespace: {{ include "sales.namespace" . }}
  labels:
    {{- include "sales.labels" . | nindent 4 }}
    app: {{ printf "%s-rp-sales-app-deploy" .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-rp-sales-app-deploy" .Release.Name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ printf "%s-rp-sales-app-deploy" .Release.Name }}
    spec:
      initContainers:
      # Wait for MySQL Service to be reachable
      - name: wait-for-mysql
        image: busybox:1.35
        command:
        - sh
        - -c
        - >
          until nc -z $MYSQL_HOST $MYSQL_PORT; do
            echo "Waiting for MySQL at $MYSQL_HOST:$MYSQL_PORT...";
            sleep 5;
          done;
          echo "MySQL is ready!";
        env:
        - name: MYSQL_HOST
          {{- if and (hasKey .Values "global") (hasKey .Values.global "salesDBRef") (ne .Values.global.salesDBRef "") }}
          from:              
            secretKeyRef:                
              name: {{ .Values.global.salesDBRef }}
              key: DB_HOST
          {{- else }}
          value: {{ printf "%s-rp-sales-sql-svc" .Release.Name }}
          {{- end }}
        - name: MYSQL_PORT
          {{- if and (hasKey .Values "global") (hasKey .Values.global "salesDBRef") (ne .Values.global.salesDBRef "") }}
          from:              
            secretKeyRef:                
              name: {{ .Values.global.salesDBRef }}
              key: DB_PORT
          {{- else }}
          value: "3306"
          {{- end }}
      containers:
      - image: {{ .Values.app.image }}
        name: {{ printf "%s-rp-sales-app-pod" .Release.Name }}
        imagePullPolicy: {{ .Values.app.imagePullPolicy }}
        ports:
          - containerPort: {{ .Values.app.port }}
        env:
        {{- if and (hasKey .Values "global") (hasKey .Values.global "salesDBRef") (ne .Values.global.salesDBRef "") }}
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.salesDBRef }}
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.salesDBRef }}
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.salesDBRef }}
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.salesDBRef }}
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.salesDBRef }}
              key: DB_PASSWORD
        {{- else }}
        - name: DB_HOST
          value: {{ printf "%s-rp-sales-sql-svc" .Release.Name }}
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-rp-sales-sql-secret" .Release.Name }}
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-rp-sales-sql-secret" .Release.Name }}
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-rp-sales-sql-secret" .Release.Name }}
              key: DB_PASSWORD
        {{- end }}
        livenessProbe:
          httpGet:
            path: /actuator/health 
            port: {{ .Values.app.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health 
            port: {{ .Values.app.port }}
          initialDelaySeconds: 20
          periodSeconds: 5
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: {{ printf "%s-rp-sales-app-cm" .Release.Name }}
{{- end }}