apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-rp-sales-app-cm" .Release.Name }}
  namespace: {{ include "sales.namespace" . }}
  labels:
    {{- include "sales.labels" . | nindent 4 }}
data:
  application.yaml: |
{{- tpl (.Values.app.configYaml |
    replace "MYSQL_HOST" (include "sales.mysqlService" .) |
    replace "INVENTORY_SVC" (include "sales.inventoryService" .) |
    replace "ORIGIN_URL" (include "sales.webURL" .) | 
    replace "ORIGIN_PORT" (include "sales.webPort" .) |
    replace "IAM_SVC" (include "sales.iamService" .) | 
    replace "IAM_PORT" (include "sales.iamPort" .)
  ) . | nindent 4 
}}