{{- if .Values.app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-rp-payment-app-svc" .Release.Name }}
  namespace: {{ .Values.namespace | default "ns-retailpulse" }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
    app: {{ printf "%s-rp-payment-app-deploy" .Release.Name }}
spec:
  selector:
    app: {{ printf "%s-rp-payment-app-deploy" .Release.Name }}
  ports:
    - port: {{ .Values.app.port | default 8087 }}
      protocol: TCP
      targetPort: {{ .Values.app.port | default 8087 }}
      nodePort: {{ .Values.app.nodePort | default 30087 }}
  type: NodePort
{{- end }}