{{- if .Values.app.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rp-payment-app-secret" .Release.Name }}
  namespace: {{ .Values.namespace | default "ns-retailpulse" }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
type: Opaque
stringData:
  STRIPE_API_KEY: {{ .Values.stripe.apiKey | default "sk_test_51SBx0NH1LGmpXQLTMttHXOrB9QNPYnWRT5bIzS5W33eDJsX836XTfHKSkwmXFNd4Crnbqwh6XKm8Lu0yoeqdSPBt00evCK3s0C" | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.stripe.webhookSecret | default "whsec_a4f1e7714e26b32a81c5fdf030687e926f18b2ef7b73df35b76ec12731efd43a" | quote }}
{{- end }}