{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rp-payment-sql-secret" .Release.Name }}
  namespace: {{ .Values.namespace | default "ns-retailpulse" }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
{{- end }}