{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-rp-payment-sql-pvc" .Release.Name }}
  namespace: {{ .Values.namespace | default "ns-retailpulse" }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage | default "1Gi" }}
{{- end }}      