{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.kafkaService" . }}
  namespace: {{ include "kafka.namespace" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app: {{ printf "%s-rp-kafka" .Release.Name }}
spec:
  selector:
    app: {{ printf "%s-rp-kafka" .Release.Name }}
  ports:
    - name: plaintext
      protocol: TCP
      port: {{ .Values.kafka.listeners.plaintext.port }}
      targetPort: {{ .Values.kafka.listeners.plaintext.port }}
      
    - name: external
      protocol: TCP
      port: {{ .Values.kafka.listeners.external.port }}      
      targetPort: {{ .Values.kafka.listeners.external.port }}
      {{- if eq .Values.kafka.portType "NodePort" }}
      nodePort: {{ .Values.kafka.listeners.external.nodePort }}
      {{- end }}
  type: {{ .Values.kafka.portType }}
{{- end }}