{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-rp-inventory-app-deploy" .Release.Name }}
  namespace: {{ include "inventory.namespace" . }}
  labels:
    {{- include "inventory.labels" . | nindent 4 }}
    app: {{ printf "%s-rp-inventory-app-deploy" .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s-rp-inventory-app-deploy" .Release.Name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ printf "%s-rp-inventory-app-deploy" .Release.Name }}
    spec:
      initContainers:
        # Wait for MySQL Service to be reachable
        - name: wait-for-mysql
          image: busybox:1.35
          command:
            - sh
            - -c
            - >
              until nc -z {{ include "inventory.mysqlService" . }} 3306; do
                echo "Waiting for MySQL at {{ include "inventory.mysqlService" . }}:3306...";
                sleep 5;
              done;
              echo "MySQL is ready!";
          env:
            - name: MYSQL_HOST
              value: {{ include "inventory.mysqlService" . }}
            - name: MYSQL_PORT
              value: "3306"

        # Wait for Redis Service to be reachable
        - name: wait-for-redis
          image: redis:7.2 # Use redis image for redis-cli
          command:
            - sh
            - -c
            - >
              until redis-cli -h {{ include "inventory.redisService" . }} -p {{ .Values.redis.port }} -a $$REDIS_PASSWORD ping; do
                echo "Waiting for Redis at {{ include "inventory.redisService" . }}:{{ .Values.redis.port }}...";
                sleep 5;
              done;
              echo "Redis is ready!";
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "inventory.redisSecretName" . }} # Use helper for secret name
                  key: REDIS_PASSWORD
            - name: REDIS_HOST
              value: {{ include "inventory.redisService" . }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}

      containers:
        - image: {{ .Values.app.image }}
          name: {{ printf "%s-rp-inventory-app-pod" .Release.Name }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "inventory.redisSecretName" . }} # Use helper for secret name
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          ports:
            - containerPort: {{ .Values.app.port }}
          livenessProbe:
            httpGet:
              path: /actuator/health # Adjust path if different
              port: {{ .Values.app.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health # Adjust path if different
              port: {{ .Values.app.port }}
            initialDelaySeconds: 20
            periodSeconds: 5
          resources: {}
      volumes:
        - name: config-volume
          configMap:
            name: {{ printf "%s-rp-inventory-app-cm" .Release.Name }}
{{- end }}            