{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-rp-inventory-sql-secret" .Release.Name }}
  namespace: {{ include "inventory.namespace" . }}
  labels:
    {{- include "inventory.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
  MYSQL_DATABASE: {{ .Values.mysql.database }}
{{- end }}