global:
  namespace: ns-retailpulse
  webURL: "https://app.retailpulse.dev"   # final public URL
  rootHost: "app.retailpulse.dev"

  iamPort: 8081
  userPort: 8082
  bePort: 8083
  inventoryPort: 8084
  salesPort: 8085
  reportPort: 8086
  paymentPort: 8087

  # Backend service DNS (internal)
  iamExternalService: "https://api.retailpulse.internal/iam/" # "retailpulse-iam-rp-iam-app-svc.ns-retailpulse.svc.cluster.local"
  userExternalService: "retailpulse-user-rp-user-app-svc.ns-retailpulse.svc.cluster.local"
  businessEntityExternalService: "retailpulse-businessentity-rp-businessentity-app-svc.ns-retailpulse.svc.cluster.local"
  inventoryExternalService: "retailpulse-inventory-rp-inventory-app-svc.ns-retailpulse.svc.cluster.local"
  salesExternalService: "retailpulse-sales-rp-sales-app-svc.ns-retailpulse.svc.cluster.local"
  reportExternalService: "retailpulse-report-rp-report-app-svc.ns-retailpulse.svc.cluster.local"
  paymentExternalService: "retailpulse-payment-rp-payment-app-svc.ns-retailpulse.svc.cluster.local"

internalIngress:
  enabled: true
  className: alb
  host: api.retailpulse.internal
  annotations:
    helm.sh/resource-policy: keep
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: retailpulse-api
    alb.ingress.kubernetes.io/group.order: "10"
    alb.ingress.kubernetes.io/certificate-arn:  arn:aws:acm:ap-southeast-1:051826728851:certificate/298e9909-8850-4eb5-858b-696ef4353b97
    external-dns.alpha.kubernetes.io/hostname: api.retailpulse.internal
  hosts:
    - path: /iam
      pathType: Prefix
      backend:
        service:
          name: retailpulse-rp-iam-app-svc
          port:
            number: 8081
  tls: []

web-app:
  app:
    enabled: true
    portType: ClusterIP

  ingress:
    enabled: true
    className: alb
    annotations:
      helm.sh/resource-policy: keep
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/group.name: retailpulse-frontend
      alb.ingress.kubernetes.io/group.order: "1"
      # If your app has /health, uncomment next line
      # alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:elasticloadbalancing:ap-southeast-1:051826728851:listener/app/k8s-retailpulseapi-8cb0989ca5/0cfdd45244a40e2a/153863d6f4470788
      external-dns.alpha.kubernetes.io/hostname: app.retailpulse.dev
    hosts:
    - host: app.retailpulse.dev
      paths:
        - path: /
          pathType: Prefix
    tls: []

iam:
  app:
    enabled: true
    port: 8081
    serviceType: ClusterIP
