global:
  namespace: ns-retailpulse
  webURL: "https://app.retailpulse.dev"   # final public URL
  rootHost: "app.retailpulse.dev"

  iamPort: 8081
  userPort: 8082
  bePort: 8083
  inventoryPort: 8084
  salesPort: 8085
  reportPort: 8086
  paymentPort: 8087

  # Backend service DNS (internal)
  iamExternalService: "retailpulse-iam-rp-iam-app-svc.ns-retailpulse.svc.cluster.local"
  userExternalService: "retailpulse-user-rp-user-app-svc.ns-retailpulse.svc.cluster.local"
  businessEntityExternalService: "retailpulse-businessentity-rp-businessentity-app-svc.ns-retailpulse.svc.cluster.local"
  inventoryExternalService: "retailpulse-inventory-rp-inventory-app-svc.ns-retailpulse.svc.cluster.local"
  salesExternalService: "retailpulse-sales-rp-sales-app-svc.ns-retailpulse.svc.cluster.local"
  reportExternalService: "retailpulse-report-rp-report-app-svc.ns-retailpulse.svc.cluster.local"
  paymentExternalService: "retailpulse-payment-rp-payment-app-svc.ns-retailpulse.svc.cluster.local"

web-app:
  app:
    enabled: true
    portType: ClusterIP

  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/group.name: retailpulse-frontend
      alb.ingress.kubernetes.io/group.order: "1"
      # If your app has /health, uncomment next line
      # alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:051826728851:certificate/6012df97-d861-4a1a-80a9-3675ecbf269d
      external-dns.alpha.kubernetes.io/hostname: app.retailpulse.dev
    hosts:
      - host: app.retailpulse.dev
        paths:
          - path: /
            pathType: Prefix
    tls: []