global:
  protocol: "http"
  rootHost: "localhost"
  rootURL: "http://localhost"
  webURL: "http://localhost:30080" # This sets .Values.global.webURL
  namespace: ns-retailpulse # This sets .Values.global.namespace
    
  autoReleaseName: 1
  iamPort: 8081
  userPort: 8082
  bePort: 8083
  inventoryPort: 8084
  paymentPort: 8087
  kafkaPort: 9092
  kafkaPaymentTopic: "payment-events"

  # Backend service DNS (internal)
  iamInternalService: "rp-iam-app-svc:8081/auth" 
  userInternalService: "rp-user-app-svc:8082/"
  businessEntityInternalService: "rp-business-entity-app-svc:8083/"
  inventoryInternalService: "rp-inventory-app-svc:8084/"
  salesInternalService: "rp-sales-app-svc:8085/"
  reportInternalService: "rp-report-app-svc:8086/"
  paymentInternalService: "rp-payment-app-svc:8087/"


  # Backend service DNS (external)
  iamExternalService: "http://localhost:30081/auth" 
  userExternalService: "http://localhost:30082/"
  businessEntityExternalService: "http://localhost:30083/"
  inventoryExternalService: "http://localhost:30084/"
  salesExternalService: "http://localhost:30085/"
  reportExternalService: "http://localhost:30086/"
  paymentExternalService: "http://localhost:30087/"

apiIngress:
  enabled: false

# web-app:
#   app:
#     enabled: false

# identity-access-management: 
#   app:
#     enabled: false

# user-microservice:
#   mysql:
#     enabled: true    
#     nodePort: 30305
#     portType: NodePort
#   app:
#     enabled: false

# business-entity-microservice: 
#   mysql:
#     enabled: true    
#     nodePort: 30307
#     portType: NodePort
#   app:
#     enabled: false

# inventory-microservice:
#   mysql:
#     enabled: true
#     nodePort: 30308
#     portType: NodePort  
#   app:
#     enabled: false

# sales-microservice:
#   mysql:
#     enabled: true
#     nodePort: 30309
#     portType: NodePort  
#   app:
#     enabled: false


# report-microservice:
#   app:
#     enabled: false

# payment-microservice:
#   mysql:
#     enabled: true
#     nodePort: 30310
#     portType: NodePort  
#   app:
#     enabled: false
