global:  
  protocol: "https"
  rootHost: "app.retailpulse.dev"
  rootURL: "https://app.retailpulse.dev"
  webURL: "https://app.retailpulse.dev"   
  namespace: ns-retailpulse

  autoReleaseName: 1
  iamPort: 8081
  userPort: 8082
  bePort: 8083
  inventoryPort: 8084
  paymentPort: 8087
  kafkaPort: 9092
  kafkaPaymentTopic: "payment-events"

  # Backend service DNS (internal)
  iamInternalService: "-rp-iam-app-svc:8081/auth" 
  userInternalService: "-rp-user-app-svc:8082/"
  businessEntityInternalService: "-rp-business-entity-app-svc:8083/"
  inventoryInternalService: "-rp-inventory-app-svc:8084/"
  salesInternalService: "-rp-sales-app-svc:8085/"
  reportInternalService: "-rp-report-app-svc:8086/"
  paymentInternalService: "-rp-payment-app-svc:8087/"


  # Backend service DNS (external)
  iamExternalService: "https://app.retailpulse.dev/auth" 
  userExternalService: "https://app.retailpulse.dev/" 
  businessEntityExternalService: "https://app.retailpulse.dev/api/businessEntity/"
  inventoryExternalService: "https://app.retailpulse.dev/api/inventory/"
  salesExternalService: "https://app.retailpulse.dev/api/sales/"
  reportExternalService: "https://app.retailpulse.dev/api/report/" 
  paymentExternalService: "https://app.retailpulse.dev/api/payment/"
    
web-app:
  app:
    enabled: true
    portType: ClusterIP
  ingress:
    enabled: true
    className: alb
    annotations:
      helm.sh/resource-policy: keep
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type:  ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/group.name: retailpulse-api
      alb.ingress.kubernetes.io/group.order: "10"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:051826728851:certificate/6012df97-d861-4a1a-80a9-3675ecbf269d
    hosts:
    - host: app.retailpulse.dev
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: retailpulse-rp-web-svc
            port:
              number: "8080"
    tls: []

identity-access-management:
  app:
    enabled: true
    image: docker.io/casperyap/rp-iam-app:v0.2.0
    port: 8081
    urlPrefix: /auth
    serviceType: ClusterIP
  ingress:
    enabled: true
    className: alb
    annotations:
      helm.sh/resource-policy: keep
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/group.name: retailpulse-api
      alb.ingress.kubernetes.io/group.order: "1"
      alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:051826728851:certificate/6012df97-d861-4a1a-80a9-3675ecbf269d
    hosts:
    - host: app.retailpulse.dev
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: retailpulse-rp-iam-app-svc
            port:
              number: 8081
      - path: /auth/.well-known
        pathType: Prefix
        backend:
          service:
            name: retailpulse-rp-iam-app-svc
            port:
              number: 8081
    tls: []

user-service:  
  app:
    enabled: true
    image: docker.io/casperyap/rp-user-app:v0.1.0
    port: 8082
    serviceType: ClusterIP


apiIngress:
  enabled: true
  className: alb
  annotations:
    helm.sh/resource-policy: keep
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: retailpulse-api
    alb.ingress.kubernetes.io/group.order: "2"
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:051826728851:certificate/6012df97-d861-4a1a-80a9-3675ecbf269d
  hosts:
  - host: app.retailpulse.dev
    paths:
    - path: /api/users
      pathType: Prefix
      backend:
        service:
          name: retailpulse-rp-user-app-svc
          port:
            number: 8082
  tls: []