name: Deploy Helm Chart to AWS EKS

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION | tr -d '\n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Verify cluster connection
        run: kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy Helm chart
        run: |
          helm upgrade --install retailpulse ./helm \
            --namespace ns-retailpulse \
            --create-namespace \
            -f ./helm/values-prod.yaml \
            --set global.imageTag=$(cat VERSION) \
            --wait --timeout 10m
