name: Destroy Infrastructure

# Trigger the workflow manually from the GitHub Actions tab
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to get access to your configuration files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up OpenTofu CLI; assumes you have a published action to do this
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          opentofu-version: 'latest'

      # Configure AWS credentials using secrets from GitHub
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # Initialize dependency selections and generate the lock file
      - name: Initialize OpenTofu
        working-directory: deploy
        run: tofu init -reconfigure

      # Destroy the infrastructure from the deploy folder
      - name: Destroy Infrastructure
        working-directory: deploy
        run: tofu destroy -auto-approve